import { FabToggleTheme, NextThemeProvider } from "@/components/themes";
import { Toaster } from "@/components/ui";
import localFont from "next/font/local";

import type { LayoutProps as RootLayoutProps } from "@/types/pages";
import type { Metadata } from "next";

import "../styles/globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextThemeProvider>
          <FabToggleTheme />
          {children}
          <Toaster />
        </NextThemeProvider>
      </body>
    </html>
  );
}
